// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Dashboard Service
Dashboard


    Schemes:
      https
    Host: localhost:9000
    BasePath: /dashboard/v1
    Version: 1.0.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
