// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Hourly hourly
// swagger:model Hourly
type Hourly struct {

	// condition
	Condition string `json:"condition,omitempty"`

	// feels like
	FeelsLike string `json:"feelsLike,omitempty"`

	// snow
	Snow string `json:"snow,omitempty"`

	// temperature
	Temperature string `json:"temperature,omitempty"`

	// time
	Time string `json:"time,omitempty"`
}

// Validate validates this hourly
func (m *Hourly) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Hourly) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Hourly) UnmarshalBinary(b []byte) error {
	var res Hourly
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
