// Code generated by go-swagger; DO NOT EDIT.

package dashboard_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "dashboard-service/models"
)

// GetPortfolioOKCode is the HTTP code returned for type GetPortfolioOK
const GetPortfolioOKCode int = 200

/*GetPortfolioOK Success

swagger:response getPortfolioOK
*/
type GetPortfolioOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Portfolio `json:"body,omitempty"`
}

// NewGetPortfolioOK creates GetPortfolioOK with default headers values
func NewGetPortfolioOK() *GetPortfolioOK {

	return &GetPortfolioOK{}
}

// WithPayload adds the payload to the get portfolio o k response
func (o *GetPortfolioOK) WithPayload(payload []*models.Portfolio) *GetPortfolioOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio o k response
func (o *GetPortfolioOK) SetPayload(payload []*models.Portfolio) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Portfolio, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetPortfolioBadRequestCode is the HTTP code returned for type GetPortfolioBadRequest
const GetPortfolioBadRequestCode int = 400

/*GetPortfolioBadRequest Bad Request

swagger:response getPortfolioBadRequest
*/
type GetPortfolioBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetPortfolioBadRequest creates GetPortfolioBadRequest with default headers values
func NewGetPortfolioBadRequest() *GetPortfolioBadRequest {

	return &GetPortfolioBadRequest{}
}

// WithPayload adds the payload to the get portfolio bad request response
func (o *GetPortfolioBadRequest) WithPayload(payload *models.SimpleResponse) *GetPortfolioBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio bad request response
func (o *GetPortfolioBadRequest) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPortfolioUnauthorizedCode is the HTTP code returned for type GetPortfolioUnauthorized
const GetPortfolioUnauthorizedCode int = 401

/*GetPortfolioUnauthorized Unauthorized

swagger:response getPortfolioUnauthorized
*/
type GetPortfolioUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetPortfolioUnauthorized creates GetPortfolioUnauthorized with default headers values
func NewGetPortfolioUnauthorized() *GetPortfolioUnauthorized {

	return &GetPortfolioUnauthorized{}
}

// WithPayload adds the payload to the get portfolio unauthorized response
func (o *GetPortfolioUnauthorized) WithPayload(payload *models.SimpleResponse) *GetPortfolioUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio unauthorized response
func (o *GetPortfolioUnauthorized) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPortfolioForbiddenCode is the HTTP code returned for type GetPortfolioForbidden
const GetPortfolioForbiddenCode int = 403

/*GetPortfolioForbidden Forbidden

swagger:response getPortfolioForbidden
*/
type GetPortfolioForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetPortfolioForbidden creates GetPortfolioForbidden with default headers values
func NewGetPortfolioForbidden() *GetPortfolioForbidden {

	return &GetPortfolioForbidden{}
}

// WithPayload adds the payload to the get portfolio forbidden response
func (o *GetPortfolioForbidden) WithPayload(payload *models.SimpleResponse) *GetPortfolioForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio forbidden response
func (o *GetPortfolioForbidden) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPortfolioNotFoundCode is the HTTP code returned for type GetPortfolioNotFound
const GetPortfolioNotFoundCode int = 404

/*GetPortfolioNotFound Not Found

swagger:response getPortfolioNotFound
*/
type GetPortfolioNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetPortfolioNotFound creates GetPortfolioNotFound with default headers values
func NewGetPortfolioNotFound() *GetPortfolioNotFound {

	return &GetPortfolioNotFound{}
}

// WithPayload adds the payload to the get portfolio not found response
func (o *GetPortfolioNotFound) WithPayload(payload *models.SimpleResponse) *GetPortfolioNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio not found response
func (o *GetPortfolioNotFound) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetPortfolioInternalServerErrorCode is the HTTP code returned for type GetPortfolioInternalServerError
const GetPortfolioInternalServerErrorCode int = 500

/*GetPortfolioInternalServerError Internal Server Error

swagger:response getPortfolioInternalServerError
*/
type GetPortfolioInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.SimpleResponse `json:"body,omitempty"`
}

// NewGetPortfolioInternalServerError creates GetPortfolioInternalServerError with default headers values
func NewGetPortfolioInternalServerError() *GetPortfolioInternalServerError {

	return &GetPortfolioInternalServerError{}
}

// WithPayload adds the payload to the get portfolio internal server error response
func (o *GetPortfolioInternalServerError) WithPayload(payload *models.SimpleResponse) *GetPortfolioInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get portfolio internal server error response
func (o *GetPortfolioInternalServerError) SetPayload(payload *models.SimpleResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPortfolioInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
