// Code generated by go-swagger; DO NOT EDIT.

package dashboard_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetHourlyWeatherParams creates a new GetHourlyWeatherParams object
// no default values defined in spec.
func NewGetHourlyWeatherParams() GetHourlyWeatherParams {

	return GetHourlyWeatherParams{}
}

// GetHourlyWeatherParams contains all the bound params for the get hourly weather operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetHourlyWeather
type GetHourlyWeatherParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*weather for the city
	  Required: true
	  In: query
	*/
	City string
	/*weather for the state
	  Required: true
	  In: query
	*/
	State string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetHourlyWeatherParams() beforehand.
func (o *GetHourlyWeatherParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qCity, qhkCity, _ := qs.GetOK("city")
	if err := o.bindCity(qCity, qhkCity, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCity binds and validates parameter City from query.
func (o *GetHourlyWeatherParams) bindCity(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("city", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("city", "query", raw); err != nil {
		return err
	}

	o.City = raw

	return nil
}

// bindState binds and validates parameter State from query.
func (o *GetHourlyWeatherParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("state", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("state", "query", raw); err != nil {
		return err
	}

	o.State = raw

	return nil
}
